### ISSUE TITLE
flask spec  RuntimeError: The data key 'data' is not found in the base response schema spec.

### ISSUE THREAD

**Issue by zhibeen** [apiflask/apiflask#574]
Environment:

- Python version:  3.9
- Flask version: 3.0.3
- APIFlask version: 2.1.1

setting.py 设置

class BaseResponseSchema(Schema):
    message = String()
    code = Integer(required=True)
    data = Field(data_key='result')  # the data key
    type = String(required=True, validate=OneOf(['success', 'error', 'warning']))
    
    # APIFLASK
    BASE_RESPONSE_SCHEMA = BaseResponseSchema
    BASE_RESPONSE_DATA_KEY = 'data'
 command 

flask spec

 error
Traceback (most recent call last):
  File "/usr/local/bin/flask", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/site-packages/flask/cli.py", line 1105, in main
    cli.main()
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/flask/cli.py", line 386, in decorator
    return ctx.invoke(f, *args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/apiflask/commands.py", line 42, in spec_command
    spec = current_app._get_spec(spec_format)
  File "/usr/local/lib/python3.10/site-packages/apiflask/app.py", line 625, in _get_spec
    spec_object: APISpec = self._generate_spec()
  File "/usr/local/lib/python3.10/site-packages/apiflask/app.py", line 1008, in _generate_spec
    self._add_response(
  File "/usr/local/lib/python3.10/site-packages/apiflask/app.py", line 1248, in _add_response
    raise RuntimeError(
RuntimeError: The data key 'data' is not found in the base response schema spec.

you do not use  data_key='result' for  class BaseResponseSchema

**Comment by uncle-lv** [comment]
Change `BASE_RESPONSE_DATA_KEY` to ‘result’, because you have specified it to 'result' instead of 'data'.
